### DISCUSSION TITLE
Better UX in long dropdowns: jump to selected item

### DISCUSSION THREAD

**Discussion by arnaudgautron** [joomla/joomla-cms#47007] [2. Cold Features]
### Steps to reproduce the issue
The issue was identified in Event Booking component but concerns Joomla 4 back-end template. When asking the development team, they told me it was a Joomla 4 back-end template issue so I write this bug report.

- Having a long dropdown in back-end with more than 7 (?) items

### Expected result

When opening dropdown, the list is supposed to jump to the selected item, even if it's "deep" in the list.
Screenshot from Joomla 3.10.11 (EventBooking 3.17.6)
![Capture d’écran 2023-03-07 à 15 07 26](https://user-images.githubusercontent.com/42864394/223472612-07728352-e7e3-429f-8f6e-35a95eb6870c.jpg)
![Capture d’écran 2023-03-07 à 15 08 05](https://user-images.githubusercontent.com/42864394/223471942-68145d41-00e4-489d-86fa-b08f5476aaf8.jpg)

### Actual result

When opening dropdown, the list starts from the beginning. You have to scroll down to the selected item position.
Screenshot from Joomla 4.2.8 (EventBooking 4.4.2)
![Capture d’écran 2023-03-07 à 15 08](https://user-images.githubusercontent.com/42864394/223472656-667619d9-620c-4306-8d2e-23be38f2bd22.jpg)
![Capture d’écran 2023-03-07 à 15 10 09](https://user-images.githubusercontent.com/42864394/223471996-76260117-5c93-4e2d-9ee7-a711e3a23566.jpg)

### System information (as much as possible)

Joomla! 4.2.8 Stable [ Uaminifu ] 16-February-2023 15:00 GMT 
PHP 8.0.28
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0 

### Additional comments
In EventBooking, we add custom CSS to set the appearance of selected item in the list:
```css
.choices__item--choice.is-selected:not(.is-highlighted)
{
background-color: var(--template-bg-dark);
color: white;
}

.choices__item--choice.is-selected.is-highlighted
{
background-color: var(--template-link-hover-color);
color: white;
} 
```
