### ISSUE TITLE
HHVM errors from Travis ci

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#10220]
This is a list of the tests which are known to be failing or have errors in the HHVM phpunit testing (allowed failures)

~~Unfortunately, due to an out memory limit error in Travis-ci I can only retrieve the names of the tests that errored or failed (test listed below)~~

I was able to get some of the test failure details by filtering and only running one test at a time.

you can see the results of my first test here https://travis-ci.org/photodude/joomla-cms/jobs/127702652

There were ~~11~~ ~~9~~ 0 errors:

~~1) [JInstallerAdapterTest::testCheckExistingExtensionForExistingExtension](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L90-L135)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:103
2) [JInstallerAdapterTest::testCheckExistingExtensionForExtensionThatDoesNotExist](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L135-L176)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:148
3) [JInstallerAdapterTest::testDiscoverInstall](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L336-L369)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:371
4) [JInstallerAdapterTest::testDiscoverInstallWithNoDescription](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L404-L473)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:439
5) [JInstallerAdapterTest::testInstall](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L787-L860)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:827
6) [JInstallerAdapterTest::testInstallOnUpdateRoute](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L860-L939)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:901
7) [JInstallerAdapterTest::testInstallAbortsWhenSetupUpdatesThrowsException](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L939-L1012)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:980
8) [JInstallerAdapterTest::testInstallWithNoDescription](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L1012-L1086)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:1052
9) [JInstallerAdapterTest::testParseQueriesWithUpdateRouteAndParsingReturningTrueCallsParseSchemaUpdatesCorrectly](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php#L1300-L1341)
UnexpectedValueException: No columns found for #__extensions table
/libraries/joomla/table/table.php:245
/libraries/joomla/table/table.php:162
/libraries/joomla/table/extension.php:30
/tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php:1330~~
See proposed PR #12990 

~~10) JDocumentHtmlTest::testEnsureMergeHeadDataReturnsThisObject
Array to string conversion
/tests/unit/core/helper/helper.php:52
/libraries/joomla/document/html.php:222
/tests/unit/suites/libraries/joomla/document/html/JDocumentHTMLTest.php:134~~ 
See merged PR #12013

~~11) JDatabaseDriverPostgresqlTest::testReleaseTransactionSavepoint
pg_result_error_field() expects parameter 1 to be resource, boolean given
/home/travis/build/photodude/joomla-cms/tests/unit/core/helper/helper.php:52
/home/travis/build/photodude/joomla-cms/libraries/joomla/database/driver/postgresql.php:1513
/home/travis/build/photodude/joomla-cms/libraries/joomla/database/driver/postgresql.php:742
/home/travis/build/photodude/joomla-cms/libraries/joomla/database/driver/postgresql.php:1384
/home/travis/build/photodude/joomla-cms/tests/unit/suites/database/driver/postgresql/JDatabaseDriverPostgresqlTest.php:1205~~
See merged PR https://github.com/joomla/joomla-cms/pull/12359
#### There were ~~3~~ 2 failures

~~Fatal error: Call to undefined function pg_set_error_verbosity() in /home/travis/build/photodude/joomla-cms/libraries/joomla/database/driver/postgresql.php on line 140~~ fixed in the release of HHVM 3.15.2

~~1) JInstallerAdapterTest::testParseQueriesWithUpdateRouteAndParsingReturningFalseReturnsException
Expectation failed for method name is equal to string:parseSchemaUpdates when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.~~ See proposed PR #12990 

~~2) JLoaderTest::testSetupWithoutPrefixes
Failed asserting that true is false.
/tests/unit/suites/libraries/joomla/JLoaderTest.php:621~~
**See facebook/hhvm#2060 for related issue to JLoaderTest**
See PR https://github.com/joomla/joomla-cms/pull/12478 for a merged internal solution

~~3) JUserHelperTest::testGetCryptedPassword
Password is hashed to crypt-blowfish without salt
Failed asserting that false is true.
/tests/unit/suites/libraries/joomla/user/JUserHelperTest.php:443~~
See merged PR https://github.com/joomla/joomla-cms/pull/12428 for a salted fix

~~At the conclusion of testing memory fails `Fatal error: request has exceeded memory limit in /libraries/vendor/phpunit/php-timer/src/Timer.php on line 97`~~ Fixed in hhvm 3.16.0 and 3.15.2

Invalid configuration directive notice
['JLanguageTest::testParse'](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/language/JLanguageTest.php#L752-L782) This gives a notice but no failure or error

**Comment by photodude** [comment]
When the HHVM php7 compatibility flag is on, the errors greatly increase. Currently tests die at about 12% [Click here to see an example build...](https://travis-ci.org/photodude/joomla-cms/jobs/131593468)

This is the error that seems to be killing the [HHVM_with_PHP7_compatibility flag](https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings) unitTests
```php
Methods with the same name as their class will not be constructors in a future version of PHP; Cache_Lite has a deprecated constructor: 1x
    1x in JCacheStorageTest::casesGetInstance
```

**Comment by mbabker** [comment]
That should only be a deprecation notice and not a failure.  That or HHVM has a behavior change compared to PHP 7.

**Comment by photodude** [comment]
According to HHVM [when the flag `hhvm.php7.all = 1` is set to fully enable PHP 7 mode](https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings) one of the things it does is "Disallow and warn when using old PHP 4 constructors"

Seems HHVM with php7 mode may be far more strict about some of the PHP7 changes.

**Comment by photodude** [comment]
At some point a decision about what HHVM LTS versions we want to test against. There is a feature request and a [PR for Travis CI that will allow Trusty supported HHVM LTS versions](https://github.com/travis-ci/travis-build/pull/733) If that PR gets merged we will have the following options 3.3, 3.6, 3.9, 3.12, and when it's released in July hhvm 3.15.

Currently, we only have the option to test against `hhvm` latest (currently 3.13 which is partialy broken), or `hhvm-nightly` (currently 3.14 dev) and with/without PHP7 mode (php7 mode for hhvm is only available in 3.11 or newer).

**Comment by photodude** [comment]
[Allow HHVM LTS version specification #733]() has been implemented and documented. 

we now have access to the following
- hhvm-3.3
- hhvm-3.6
- hhvm-3.9
- hhvm-3.12
- hhvm
- hhvm-nightly

note: hhvm is latest (not always an LTS version), and hhvm-nightly is current nightly dev of HHVM

I suggest not testing against LTS versions older than 3.12since that is the first LTS with an option for php7 mode

That would suggest a maximum HHVM build matrix option as follows
```yml
    - php: hhvm-3.12
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="no" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
    - php: hhvm-3.12
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="yes" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="no" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="yes" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="no" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        #- postgresql
        #- memcache
        #- memcached
        - redis-server
      env: HHVMPHP7="yes" INSTALL_APCU="no" INSTALL_APCU_BC_BETA="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm-3.12
    - php: hhvm
    - php: hhvm-nightly
before_script:
  - composer install
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
```

This travis build matrix will build 6 versions of HHVM
- hhvm-3.12
- hhvm-3.12 (with PHP7 mode)
- hhvm
- hhvm (with PHP7 mode)
- hhvm-nightly
- hhvm-nightly (with PHP7 mode)
