### ISSUE TITLE
Popover styling

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11256]
Tooltips have been changed in current staging to use popover (great) but there is a small styling issue - see screenshot

![overlay](https://cloud.githubusercontent.com/assets/1296369/17077447/17fcb996-50d1-11e6-9654-719361d649cb.png)

**Comment by dgt41** [comment]
quick fix:
add min-height to popover-content class
```css
.popover-content {
	padding: 9px 14px;
	min-height: 33px;
}
```
