### ISSUE TITLE
JToolbarButtonPopup doesn't respect passed width and height

### ISSUE THREAD

**Issue by fede91it** [joomla/joomla-cms#12747]
### Steps to reproduce the issue

```php
$bar = JToolbar::getInstance('toolbar');
$bar->appendButton('Popup', 'search', \JText::_('JGLOBAL_PREVIEW'), \JRoute::_($previewUrl), 800, 600);
```

### Expected result

The preview popup is 800x600 pixels.

### Actual result

The preview width and height aren't respected.

### System information (as much as possible)

Joomla 3.6.4

### Additional comments

I see that ISIS template.css set

```css
.modal-body {
    max-height: 400px;
}
```

that overrides my declared height, and respectively

 ```css
.modal-body iframe {
    width: 100%;
}
```

that overrides my declared width.
