### ISSUE TITLE
Large btn class = Joomla! Admin

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13066]
### Steps to reproduce the issue
Clear all Joomla! Post-Install Messages
### Expected result
I think it should be adjust to blend in with the template more like:
![screen shot 2016-12-02 at 21 20 30](https://cloud.githubusercontent.com/assets/1400982/20850875/6feb15e6-b8d5-11e6-8bd1-c67ffb66d2c7.jpg)
### Actual result
But it currently looks like:
![screen shot 2016-12-02 at 21 20 46](https://cloud.githubusercontent.com/assets/1400982/20850870/66bc18bc-b8d5-11e6-9fb0-65ffb0688273.jpg)
### System information (as much as possible)
Joomla! 3.7
### Additional comments

Keeps with formatting, let me know if you agree and I'll submit the pull.

**Comment by brianteeman** [comment]
It doesn't look like that to me.please recheck 
![screen shot 2016-12-03 at 02 22 21](https://issues.joomla.org/uploads/1/25cd2b65894510267559a4bd62313cf4.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13066">issues.joomla.org/tracker/joomla-cms/13066</a>.</sub>

**Comment by zero-24** [comment]
Brian Did you check on 3.7?

**Comment by brianteeman** [comment]
i checked an early 3.7 - now I check the current staging i see the problem. Looks like it will come from the re-paint PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13066">issues.joomla.org/tracker/joomla-cms/13066</a>.</sub>

**Comment by brianteeman** [comment]
@ciar4n can you take a look at this regression please

**Comment by infograf768** [comment]
the css is now
```css
.btn-large {
	padding: 11px 19px;
	font-size: 16.25px;
	-webkit-border-radius: 30px;
	-moz-border-radius: 30px;
	border-radius: 30px;
}
```
It should be imho something like
```css
.btn-large {
	padding: 11px 19px;
	font-size: 16.25px;
	-webkit-border-radius: 30px;
	-moz-border-radius: 30px;
	border-radius: 7px;
        font-weight: 400;
}
```
