### ISSUE TITLE
[com_fields] Contact: Messed Value in "Show User Custom Field"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13594]
### Steps to reproduce the issue
"Contacts: Edit" > Tab "Display": Field "Show User Custom Field" Text inside Value is messed:
![bildschirmfoto 2017-01-15 um 09 10 46](https://cloud.githubusercontent.com/assets/8235763/21961180/0e477af0-db03-11e6-84ad-ab3b5aee7ec6.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by laoneo** [comment]
If you click on it and then release it, the full text is shown. Don't know i this is a bug in the JS library @dgt41, @infograf768 any clue why this can happen.
In the meantime, I created a PR #13607 which fixes that field at all as it is broken.

**Comment by infograf768** [comment]
Element style gets a fixed width of 90px.
I get the same error when I create and display a usergroup custom field for any extension.

**Comment by laoneo** [comment]
So is this something we can solve?

**Comment by infograf768** [comment]
Looked at the js files loaded and did not see any difference.

I could sove it locally by adding 
`min-width: 187px !important;`
in chosen.css
in
```css
.chzn-container-multi .chzn-choices li.search-field input[type="text"] {
  margin: 1px 0;
  padding: 0;
  height: 25px;
  outline: 0;
  border: 0 !important;
  background: transparent !important;
  box-shadow: none;
  color: #999;
  font-size: 100%;
  font-family: sans-serif;
  line-height: normal;
  border-radius: 0;
  min-width: 187px !important;  /// Added here.
}
```
I don't know of any chzn which uses in Joomla a width below 187px.

**Comment by laoneo** [comment]
So should we add that rule to the Isis template of what is your suggestion?

**Comment by infograf768** [comment]
It certainly would work is we add:
```css
.chzn-container-multi .chzn-choices li.search-field input[type="text"] {
  min-width: 187px !important; 
}
```
in  ROOT/administrator/templates/isis/less/chzn-override.less
and then run generatecss.php cli which will add this in isis both template css files.

But it looks like a hack to me as the issue is likely to be in the implementation of com_fields.
@Bakual @dgt41 
What do you think?
