### ISSUE TITLE
[regression] Red for "Unpublished"

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#14832]
### Steps to reproduce the issue
the Status parameter is in Green color for "Published" but white for "Unpublished", in module or article settings, for me is better red color for "Unpublished" like in the 3.6.5 version

### Expected result

![http://www.alexred.com/joomla/search365.png](http://www.alexred.com/joomla/search365.png "http://www.alexred.com/joomla/search365.png")

### Actual result
![http://www.alexred.com/joomla/module-unpublished.png](http://www.alexred.com/joomla/module-unpublished.png "http://www.alexred.com/joomla/module-unpublished.png")

### System information (as much as possible)
3.7.0 nightly

**Comment by brianteeman** [comment]
@ciar4n can you take a look please - it looks like a missing class in the chosen css override

**Comment by khikmatullaev** [comment]
It is work correctly in Joomla 3.6
![image](https://cloud.githubusercontent.com/assets/11577281/24154841/92aeb736-0e52-11e7-89d2-051f6f84431d.png)

**Comment by franz-wohlkoenig** [comment]
@khikmatullaev @AlexRed compares 3.6 to 3.7

**Comment by infograf768** [comment]
The css has changed drastically:
we had before
```css
.chzn-color.chzn-single[rel="value_0"],
.chzn-color-reverse.chzn-single[rel="value_1"],
.chzn-color-state.chzn-single[rel="value_0"],
.chzn-color-state.chzn-single[rel="value_-1"],
.chzn-color-state.chzn-single[rel="value_-2"],
.chzn-color.chzn-single[rel="value_hide"] {
	color: #fff;
	text-shadow: 0 -1px 0 rgba(0,0,0,0.25);
	background-color: #ad312b;
	background-image: -moz-linear-gradient(top,#bd362f,#942a25);
	background-image: -webkit-gradient(linear,0 0,0 100%,from(#bd362f),to(#942a25));
	background-image: -webkit-linear-gradient(top,#bd362f,#942a25);
	background-image: -o-linear-gradient(top,#bd362f,#942a25);
	background-image: linear-gradient(to bottom,#bd362f,#942a25);
	background-repeat: repeat-x;
	filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffbd362f', endColorstr='#ff942a24', GradientType=0);
	border-color: #942a25 #942a25 #571916;
	*background-color: #942a25;
	filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
}
```
