### ISSUE TITLE
[4.0][RTL] CSS logical properties

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28546]
The majority of Joomla's RTL CSS is made up of corrections to left and right margins, paddings, borders, and floats. 

LTR example...

```css
.element {
  margin-left: 1rem;
}
```

RTL correction...
```css
.element {
  margin-left: auto;
  margin-right: 1rem;
}
```

As we no longer support IE11, these can all be replaced with logical properties..

LTR example...

```css
.element {
  margin-inline-start: 1rem;
}
```

RTL correction...
```
// None required. Margin is automatically flipped on RTL
```

Ref: 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
https://www.w3.org/TR/css-logical-1/

**Comment by ciar4n** [comment]
Note: Considering Bootstrap 5 will not support IE11 (https://github.com/twbs/bootstrap/pull/30377), it will most likely use logical properties.

**Comment by brianteeman** [comment]
presumably you have to define the writing mode somewhere?

**Comment by ciar4n** [comment]
Works the same as other RTL supporting properties (eg. flex) where instead of left and right, you have start and end. With `dir="ltr"`, start is on the left. With `dir="rtl"`, start is on the right.

**Comment by brianteeman** [comment]
maybe i read the docs wrongly but it looked to me that you need to have something like

### English 
```
html {
    writing-mode: horizontal-tb;
    direction: ltr;
}

```

### Arabic
```
html {
    writing-mode: horizontal-tb;
    direction: rtl;
}
```

**Comment by ciar4n** [comment]
In this instance it is not required. `writing-mode: horizontal-tb;` is default and does not need to be set. Joomla sets a `dir=""` attribute to the html tag which works as an alternative to `direction`.

**Comment by brianteeman** [comment]
ok thats great. i just didnt see anything in the docs you linked to about direction. 

I am  definitely in favour of this concept

**Comment by infograf768** [comment]
Warning though:
There are some cases where we force LTR when in RTL. They should be considered if a general patch is proposed.

**Comment by ciar4n** [comment]
Ideally you should not have to. These recent additions to the CSS spec are to eliminate the need for 'RTL' specific CSS. So for example.

You want text alignment to switch  from left to right in RTL you would use...

```css
.element {
  text-align: start;
}
```

You want text alignment to be always on the left regardless of LTR/RTL you would use..
```css
.element {
  text-align: left;
}
```
