### ISSUE TITLE
[4.0] Doubled package step in Drone since recent merge up of 3.10-dev to 4.0-dev

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#29013]
With the merge up from 3.10-dev to 4.0-dev of today, there was following change for drone.yml merged:

https://github.com/joomla/joomla-cms/pull/29010/files#diff-3216dfff0ed3e301453e6799e8c367e2

Since this we have 2 steps in drone jobs which seem to do the same, beside a slisghtly different name (packager versus package) and the fact that one of them runs in a separate pipeline.

![j4-drone-packager-doubled](https://user-images.githubusercontent.com/7413183/81483640-f63cdc00-923f-11ea-8e39-2e44be8ceed6.png)

Question: Do these jobs the same, so that one of them is a duplicate and so obsolete now? To me it seems so.

Ping @wilsonge .

**Comment by wilsonge** [comment]
Possibly. No clue which is the “desired” one tho. @HLeithner ?

**Comment by richard67** [comment]
In .drone.yml (secret names replaced by `XXXX`:
```
  - name: packager
    image: joomlaprojects/docker-images:packager
    environment:
      FTP_USERNAME:
        from_secret: XXXX
      FTP_PASSWORD:
        from_secret: XXXX
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      HTTP_ROOT: "https://ci.joomla.org/artifacts"
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
      DRONE_COMMIT: DRONE_COMMIT
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - /bin/drone_build.sh
    volumes:
      - name: reference
        path: /reference
    when:
      branch:
        - 4.0-dev
```
and then below:
```
kind: pipeline
name: package

steps:
  - name: packager
    image: joomlaprojects/docker-images:packager
    environment:
      FTP_USERNAME:
        from_secret: XXXX
      FTP_PASSWORD:
        from_secret: XXXX
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      HTTP_ROOT: "https://ci.joomla.org/artifacts"
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
      DRONE_COMMIT: DRONE_COMMIT
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - if [ $DRONE_REPO_NAME != 'joomla-cms' ]; then echo "The packager only runs on the joomla/joomla-cms repo"; exit 0; fi
      - /bin/drone_build.sh
```
The 2nd one is the one with the own pipeline, merged up from 3.10-dev, the first one is the one originally from 4.0-dev.
