### ISSUE TITLE
[4.0 Beta5] Installation not working on PHP 7.4.12

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#31691]
### Steps to reproduce the issue

Install MAMP on a Mac (clean install done)
Create a new host PHP Version 7.4.12
Install Joomla! (db server:localhost / root / root / encryption default)

### Expected result

Joomla 4 Beta 5 will work

### Actual result

Different Errors, most common: no admin user where created in database, other errors (also multiple times) leads to a similar behavior where some data in the db is missing.

From time to time errors while installation (last step) security Token error... if you then check the backend you cannot login even in those cases where an admin where created some other wild errors occured like if the server would be offline or the db is not available.

### System information (as much as possible)

MacBook Air M1 (Silicon)
MacOS 11.1
MAMP Pro Version 6.3
PHP Version 7.4.12
MySQL 5.7.32
Latest Version of Chrome & Safari

### Additional comments

Same Host: After changing to PHP 7.3.24 and deleting the configuration.php the setup runs smooth and
Joomla looks stable afterwards.

**Comment by PhilETaylor** [comment]
Im sure if this were a real issue we would have seen more reports of it by now. 3.35% of all (reporting) Joomla sites using PHP 7.4 at the moment. 

I just build a complete stack from scratch (dockerized containers) with PHP 7.4.12 and I was able to install and use Joomla 3 with no issues. 

I tried again with the [Joomla provided docker images](https://hub.docker.com/_/joomla) for PHP 7.4 which gave 7.4.13 and that too was ok, built from docker-compse.yaml 

```
version: '3.1'

services:
  joomla:
    image: joomla:php7.4
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```

I'm sorry I cannot, even though I have taken considerable time to test, I cannot replicate any of your reported issues. 

MAYBE this is a M1/Silicon and MAMP issue only - or a PHP configuration issue.
