### ISSUE TITLE
[3.10] Call to upgrade to Joomla 3.2.7 after fresh install of Joomla 3.10

### ISSUE THREAD

**Issue by Llewellynvdm** [joomla/joomla-cms#34648]
### Steps to reproduce the issue
Install a Joomla 3.10 website from the https://github.com/joomla/joomla-cms/releases/download/3.10.0-alpha7/Joomla_3.10.0-alpha7-Alpha-Full_Package.zip file. Login to the back-end of the website, and then after a few seconds the following message comes up:

![image](https://user-images.githubusercontent.com/5607939/123796657-a4dd2980-d8e5-11eb-81cd-ed604759be27.png)

### Expected result
No request to upgrade to older version of Joomla.

### Actual result
You are requested to upgrade to Joomla 3.2.7

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On | Linux 9f5db998bdd4 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64
Database Type | mysql
Database Version | 5.7.34
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.4.13
Web Server | Apache/2.4.29 (Ubuntu)
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.10.0-alpha7 Alpha [ Amani ] 13-June-2021 13:44 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0

### Additional comments
I am using this [docker build](https://github.com/vdm-io/Joomla-Docker-Fun) to deploy this instance, I have made this instance available so you can pull and test it easy. Here is the docker-compose file:
```yml
version: '2'

services:
  JTT_web:
    # image created for this task
    image: vdmio/joomla:3.10.0-alpha7
    container_name: JTT_joomla
    restart: unless-stopped
    environment:
      WEBSITEDOMAIN: jtt.localhost
      WEBSITESNAME: "Joomla 3.10"
      WEBSITESUNAME: "YourName"
      WEBSITESUSERNAME: username
      WEBSITESUSERPASS: strongpassword
      WEBSITESPASSRESET: 0
      WEBSITESEMAIL: "joomla@localhost"
      DBDRIVER: mysqli
      DBHOST: JTT_mysql
      DBUSER: jthreeten
      DBPASS: strongpassword
      DBROOTPASS: strongpassword
      DBNAME: jthreeten
      DBPREFIX: jtt
      SMTPHOST: JTT_mailcatcher
      STARTUP_COMMAND_1: deploy_joomla
    links:
      - JTT_mysql
      - JTT_mailcatcher
    depends_on:
      - JTT_mysql
    volumes:
       # To set persistence
       # - '/home/cloud/projects/JTT_joomla:/var/www/html'
       # To remove persistence
       - web-root:/var/www/html
    networks:
      - JTT-NETWORK
    ports:
      - 380:80
      - 3443:443

  JTT_mysql:
    image: mysql:5.7
    container_name: JTT_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
       # To set persistence
       # - '/home/cloud/projects/JTT_db-data:/var/lib/mysql'
       # To remove persistence
       - db-data:/var/www/html
    networks:
      - JTT-NETWORK

  JTT_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: JTT_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: JTT_mysql
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: strongpassword
    links:
      - JTT_mysql
    networks:
      - JTT-NETWORK
    ports:
      - 381:80

  JTT_mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    container_name: JTT_mailcatcher
    networks:
      - JTT-NETWORK
    ports:
      - 382:1080

networks:
  JTT-NETWORK:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24

# To remove persistence
volumes:
   web-root:
   db-data:
```
Once the container is running and Joomla is finished installing. You can login with your details and go to `http://jtt.localhost/administrator/index.php?option=com_installer&view=manage` if you setup the local domain... anyway you will need to refresh cache of all extensions. Then go to the control panel and you will see this message.
