### ISSUE TITLE
[4.0] "(TEMPORARY)" css rules in main cassiopea template.scss

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#35714]
### Problem identified
In [cassiopeia/scss/template.scss](https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/template.scss#L52-L60) we have "temporary" css rules:
```css
// Chosen (TEMPORARY)
.chzn-container-single {
  width: auto !important;
}

.chzn-container-multi {
  width: 100% !important;
  max-width: 240px;
}
```

### Proposed solution
Remove / Transfer to a more suitable file. 

### Open questions

It is also present in [/administrator/templates/atum/scss/blocks/_global.scss](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_global.scss#L157-L160)

```css
// Chosen (TEMPORARY)
.chzn-container-single {
  width: auto !important;
}
```
