### ISSUE TITLE
[4.0.4, atum] No columns on Options tab on lg screens

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#35997]
### What needs to be fixed
In articles, menu, ... (I don't check others) on `Options` tabs `lg` layout is one column. In previous versions (probably before bootstrap 5 / grid) it was 3 columns

![image](https://user-images.githubusercontent.com/11570/140943211-e00b51c6-bf92-40ff-9bf1-a8c98db7bf1a.png)
Left: Joomla 4.0.4; Right: Joomla beta5-dev (approx 1 years older, bootstrap 4)

### Why this should be fixed
Tradition xD

Waste of space in width, the page stretches a lot. 

### How would you fix it

I see, that form rows has only class `control-group`.  They should have also `span-2-inline` class.

Also to `.control-group` should be add `flex-direction: column;`

```css
 .form-grid .span-2-inline {
  grid-column:var(--span-2)
 }
.form-grid .span-2 {
 grid-column:1/var(--span-2)
}

```

I see, that is defined:
```css
.form-grid > * {
    grid-column: 1/-1;
}
.form-grid {
    --span-3: span 3;
    --span-4: span 4;
    --span-5: span 5;
    grid-template-columns: repeat(6,1fr);
}
 .form-grid {
  --span-2:span 2;
  --span-3:span 2;
  --span-4:span 2;
  --span-5:span 2;
  grid-template-columns:repeat(2,1fr)
 }
}
@media (min-width:1400px) {
 .form-grid {
  --span-3:span 3;
  --span-4:span 4;
  --span-5:span 5;
  grid-template-columns:repeat(6,1fr)
 }
```
But I can't see where **--span-_n_** variables are used.
