### ISSUE TITLE
[4.3] Missing colors language debugbar

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#39651]
### Steps to reproduce the issue

- Enable language debug
- Open debug bar

```html
<tr>
    <td>joomla</td>
    <td>
        <ul>
            <li class="alert-success">+ \administrator/language/en-GB/joomla.ini</li>
        </ul>
    </td>
</tr>
```

### Expected result

![image](https://user-images.githubusercontent.com/66922325/212766657-a4a19216-6a88-452f-9310-6dac5c343469.png)

```css
.alert-success {
  color: #294b32;
  background-color: #dae5dd;
  border-color: #c7d8cc;
}
```

### Actual result

![image](https://user-images.githubusercontent.com/66922325/212766629-261406bd-f03c-416e-96b7-f08313b29070.png)

```css
.alert-success {
  --alert-color: #294b32;
  --alert-bg: #dae5dd;
  --alert-border-color: #c7d8cc;
}
```

### System information (as much as possible)

J4.3-dev

### Additional comments

If I revert PR #39379 (Bootstrap update) it works @dgrammatiko
