### ISSUE TITLE
[4.3] Display of readonly list field changed 

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#40349]
### Steps to reproduce the issue

Login/Create an user who don't have access for `core.edit.state` and check the `published` form field

### Expected result

J4.2.10-dev
![image](https://user-images.githubusercontent.com/66922325/230772290-3c9bb897-fb4f-4d08-a1a3-247448972eab.png)

### Actual result

J‎4.3.0-rc3-dev
![image](https://user-images.githubusercontent.com/66922325/230772302-5fb5b455-a2cd-4ba6-a233-e65524478b6c.png)

### Additional comments

That's the difference I found and maybe related to PR #39379 and @dgrammatiko can help?

J4.2.10-dev
```css
.form-select:disabled, .custom-select:disabled {
  cursor: default;
  background: #e8e8e8;
  border: 0;
  -webkit-box-shadow: none;
          box-shadow: none;
}
```

J‎4.3.0-rc3-dev
```css
.form-select:disabled, .custom-select:disabled {
  cursor: default;
  border: 0;
  -webkit-box-shadow: none;
          box-shadow: none;
}
```
